### ISSUE TITLE
Resources for studying from home 

### ISSUE THREAD

**Issue by WeileiZeng** [worldimprovementlab/coronavirus-cheatsheet#1]
https://docs.google.com/spreadsheets/d/1O3wnaFYSZCgY3Ih4yDw3EIH2SC_-vjhyHwrCQSy0J7M/htmlview?fbclid=IwAR3Z5VxuKicyB5h0dAIRhU5TtZq78dzFBZ45f8G7fI1sBhWEyFIj5rGibME#

As many universities turn to online instruction, many of them may need guidance for technique support and policy. This list and many other lists linked in its page, are helpful.

**Comment by WeileiZeng** [comment]
Do you have a website other than this repo?

**Comment by pydanny** [comment]
Hi @WeileiZeng, we just got https://coronavirus.cheatsheet.zone/ working. We also own the domain for coronaviruscheatsheet.org, which I'm working on right now.

**Comment by pydanny** [comment]
I just got https://coronaviruscheatsheet.org/ working. Check it out!

**Comment by WeileiZeng** [comment]
Great! I updated the link to my open source list
https://weileizeng.github.io/Open-Source-COVID-19/

**Comment by pydanny** [comment]
Since we have your submitted list up on the site, as well as https://weileizeng.github.io/Open-Source-COVID-19/, I'm closing this ticket. 

Also, thank you @WeileiZeng for putting together your site and inspiring us to get our project up. <3
